baseRepoURL: https://github.com/hdti-devops/hdti-gitops.git
basePath: clusters/hdti/tenants/dev/core/

apps:
  nginxIngress:
    targetRevision: HEAD
    path: nginx-ingress
    namespace: nginx-ingress

  externalSecrets:
    targetRevision: HEAD
    path: external-secrets
    namespace: external-secrets
    vaultClusterStore: true