baseRepoURL: https://github.com/hdti-devops/hdti-gitops.git
basePath: clusters/hdti/tenants/dev/core/

apps:
  metallb:
    targetRevision: HEAD
    path: metallb
    namespace: metallb-system

  externalSecrets:
    targetRevision: HEAD
    path: external-secrets
    namespace: external-secrets

  nginxIngress:
    targetRevision: HEAD
    path: nginx-ingress
    namespace: nginx-ingress

  certManager:
    targetRevision: HEAD
    path: cert-manager
    namespace: cert-manager