apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../../../charts

helmCharts:
  - name: external-secrets
    namespace: external-secrets
    releaseName: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.2.0
    includeCRDs: true
  - name: external-secrets-tools
    namespace: external-secrets
    releaseName: external-secrets-tools
    version: external-secrets-tools-v1.2.1 #release by release please

patches:
  - target:
      group: external-secrets.io
      version: v1
      kind: ClusterSecretStore
      name: vault # Ensure this matches the metadata.name of your store
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io/sync-wave
        value: "2"