apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: {{ .Values.baseRepoURL }}
    targetRevision: {{ .Values.apps.externalSecrets.targetRevision }}
    path: {{ .Values.basePath }}{{ .Values.apps.externalSecrets.path }}
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.externalSecrets.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data/password
  