apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ .Values.apps.external-secrets.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.apps.external-secrets.syncWave }}
spec:
  project: default
  source:
    repoURL: {{ .Values.baseRepoURL }}
    targetRevision: {{ .Values.apps.external-secrets.targetRevision }}
    path: {{ .Values.basePath }}{{ .Values.apps.external-secrets.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.external-secrets.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
    ignoreDifferences:
      - group: ""
        kind: Secret
        jsonPointers:
          - /data/password
  