apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.baseRepoURL }}
    targetRevision: {{ .Values.apps.metallb.targetRevision }}
    path: {{ .Values.basePath }}{{ .Values.apps.metallb.path }}
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.metallb.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
  