apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../../../charts

helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: v1.20.0
    includeCRDs: true
  - name: cert-manager-tools
    namespace: cert-manager
    releaseName: cert-manager-tools
    version: cert-manager-v1.0.0 #release by release please

# Force ArgoCD to wait for cert-manager to be healthy before tools
patches:
  # Patch for cert-manager-tools resources (Issuers, Certificates)
  - target:
      group: cert-manager.io
      kind: (ClusterIssuer|Issuer|Certificate)
    patch: |
      apiVersion: cert-manager.io/v1
      kind: unused
      metadata:
        name: unused
        annotations:
          argocd.argoproj.io/sync-wave: "4"