
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../../../charts

helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: v1.20.0
    includeCRDs: true
    valuesInLine:
      crds:
        enabled: true
      extraArgs:
        - --tls-ca-file=/etc/ssl/certs/step-ca.crt
  - name: cert-manager-tools
    namespace: cert-manager
    releaseName: cert-manager-tools
    version: cert-manager-tools-v1.4.2 #release by release please

patches:
  - path: cert-manager-patch.yaml