---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}-issuer
spec:
  acme:
    # Step CA ACME endpoint
    server: https://step-ca.hdti.ca/acme/acme/directory
    email: {{ .Values.clusterIssuer.email}}
    privateKeySecretRef:
      name: step-ca-account-key
    # Trust your internal Step CA root
    caBundle: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvekNDQVVxZ0F3SUJBZ0lSQVBwN1RDWEVjZkYwaWdVSHZUazZqaGN3Q2dZSUtvWkl6ajBFQXdJd01ERVMKTUJBR0ExVUVDaE1KVFhsSWIyMWxVRXRKTVJvd0dBWURWUVFERXhGTmVVaHZiV1ZRUzBrZ1VtOXZkQ0JEUVRBZQpGdzB5TmpBek1qUXhNelF5TVROYUZ3MHpOakF6TWpFeE16UXlNVE5hTURBeEVqQVFCZ05WQkFvVENVMTVTRzl0ClpWQkxTVEVhTUJnR0ExVUVBeE1SVFhsSWIyMWxVRXRKSUZKdmIzUWdRMEV3V1RBVEJnY3Foa2pPUFFJQkJnZ3EKaGtqT1BRTUJCd05DQUFRYWZSQTlXN2toclM3cVVpNWoxMURZSGozVVlIMzdPR29DMVY4RU1XRDNpRW9vOTdEbAp5Qk9WVVlocmU2bzlCdWhaRlFPSWNuay9GNzdtMmRRY1NlM01vMFV3UXpBT0JnTlZIUThCQWY4RUJBTUNBUVl3CkVnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQWRCZ05WSFE0RUZnUVVydEVSa2RuZXpjRmhEUTR0QkRZaTZyNVQKU0ZRd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ0lwMWhTajJYRWlmQXpNL3NVNzJUVW95RkROS3Z2bXdEZk0xZQoxWGN4RE9zQ0lCUnZaTkNJL0ZaOWpoT1Q1YUoySkNVMExyWlJCcUxsOEdBZjBSSjhLMXZVCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K'
    solvers:
    - dns01:
        rfc2136:
          nameserver: {{ .Values.clusterIssuer.nameserverIp }} # Technitium DNS IP
          tsigAlgorithm: HMACSHA256
          tsigKeyName: cert-manager-key
          tsigSecretSecretRef:
            name: {{ .Values.eso.tsig.name }}          # Kubernetes Secret containing TSIG key
            key: {{ .Values.eso.tsig.property }}       # Key name inside the Secret