---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}-cluster-issuer
spec:
  acme:
    email: {{ .Values.clusterIssuer.email}}         # <-- Replace with your email
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-account-key    # ACME account key secret
    solvers:
      - dns01:
          webhook:
            groupName: acme.hdti.ca
            solverName: technitium-dns