---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}-issuer
spec:
  acme:
    # Step CA ACME endpoint
    server: https://step-ca.hdti.ca/acme/acme/directory
    email: {{ .Values.clusterIssuer.email}}
    privateKeySecretRef:
      name: step-ca-account-key
    solvers:
    - dns01:
        rfc2136:
          nameserver: {{ .Values.clusterIssuer.nameserverIp }} # Technitium DNS IP
          tsigAlgorithm: HMACSHA256
          tsigKeyName: cert-manager-key
          tsigSecretSecretRef:
            name: {{ .Values.eso.tsig.name }}          # Kubernetes Secret containing TSIG key
            key: {{ .Values.eso.tsig.property }}       # Key name inside the Secret