apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.eso.tsig.name }}
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.eso.tsig.name }}
  data:
  - secretKey: {{ .Values.eso.tsig.property }}
    remoteRef:
      key: {{ .Values.eso.tsig.path }}
      property: {{ .Values.eso.tsig.property }}