apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

helmCharts:
  - name: nginx-ingress
    namespace: nginx-ingress
    releaseName: nginx-ingress
    repo: oci://ghcr.io/nginx/charts
    version: 2.5.0
    includeCRDs: true
    valuesInLine:
      controller:
        service:
          type: LoadBalancer
          loadBalancerIP: "192.168.0.240"
          annotations:
            metallb.universe.tf/loadBalancerIPs: "192.168.0.240"

      