apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

helmCharts:
  - name: nginx-nginx
    namespace: nginx-ingress
    releaseName: nginx-ingress
    repo: oci://ghcr.io/nginx/charts
    version: 2.5.0
    includeCRDs: true